#=======================
# Experiment
#=======================

experiment:
  seed: 42

paths:
  data_root: "/storage/home/hcoda1/1/bostrower3/r-bzhu36-0/PhysicsSim/Data/"
  data_folder: "Deforming_Plate"
  wandb_dir: "./wandb"

#=======================
# Weights and Biases
#=======================
wandb:
  checkpoint_dir: "."
  project: "MeshGraphNet"
  name: "Intitial_Run"


#=======================
# Dataset/Dataloader
#=======================

data:
  noise:
    enabled: True
    std: 0.003
    gamma: 0.1
    for_features: ['world_pos','velocity']
    for_targets: ['velocity']


#=======================
# Features
#=======================
Node_Features:
  # Dataset Common
  - world_pos
  - stress
  - node_type
  #- velocity

  #Deforming Plate
  - scripted_motion

  #Impact Plate
  #- density
  #- youngs_modulus

#=======================
# Model Selection
#=======================

model:
  type: "MGN"
  radius: 0.03

  MGN:
    output_size: 4
    node_encoder_input_size: 16
    mesh_edge_encoder_input_size: 8
    world_edge_encoder_input_size: 4
    latent_size: 128
    num_mlp_layers: 2
    message_passing_steps: 10

  HCMT:
    output_size: 4
    node_encoder_input_size: 27
    mesh_edge_encoder_input_size: 8
    world_edge_encoder_input_size: 4
    latent_size: 128
    num_mlp_layers: 2
    num_attention_heads: 4

#=======================
# Optimizer
#=======================

optim:
  type: "Adam"
  lr: 1e-4
  weight_decay: 1e-6

#=======================
# Training
#=======================
training:
  epochs: 5
  normalizer_steps: 1000


#=======================
# Eval
#=======================
Eval:
  model_name: best_model.pt
  num_rollouts: 10
  Pickle_name: Rollout.pkl
  Eval_MSE_Steps: [1,24,49,74,99,124,149,174,199,224,249,274,299,324,349,374,399]

#=======================
# Plotting
#=======================
Plot:
  plot_name: giffy.gif
  num_rollouts: 10
  Pickle_name: Rollout.pkl
